js/framework/AnalyticsConstants.js, test/unit-tests/testAnalyticsFramework.js
I added some classes for the data that gets sent along with messages and a lot of documentation.
=> Pbi 1220 1

js/framework/AnalyticsConstants.js, js/framework/AnalyticsFramework.js, js/framework/InitAnalyticsNamespace.js, js/plugins/AnalyticsPluginTemplate.js
See commit messages for details of what was changed.
=> JSDoc updates

js/plugins/omniture.js, package.json, test/unit-test-helpers/mock_adobe.js, test/unit-tests/testOmniture.js
-fixed an issue where evars and props were not set properly
-fixed an issue where omniture unit test coverage was not reported
=> [omni-evar-prop]

js/framework/AnalyticsConstants.js
-Added VIDEO_ELEMENT_CREATED event, along with its corresponding Data object
-some cleanup
=> [publish-stream-urls]

js/plugins/Nielsen.js, test/unit-tests/testNielsen.js
-fixed an issue where assetid was not provided to Nielsen’s content metadata
=> [PBI-1758]

test/unit-test-helpers/AnalyticsFrameworkTestUtils.js
-using defined COMMON_SRC_ROOT
=> [fix-build]

js/plugins/omniture.js, test/unit-tests/testOmniture.js
Omniture:
-fixed an issue where the SDK would think we are playing an ad when we are playing main content
=> [PBI-1771]

js/plugins/Nielsen.js, test/unit-tests/testNielsen.js
Implemented Nielsen’s suggestions
-event 49 position updates are now floored
-fixed issue where reported ad durations could be 1 second less than the actual duration
-fixed an issue where we do not report playhead positions if we seek backwards until we hit the largest seen playhead
-changed adloadtype to 2
-updated default SDK url to latest version
-provide SDK with new param nsdkv with value “511”
-nol_sdkDebug will now use the value “DEBUG” and allowed page level control of enabling debug sdk
=> [PBI-1733]

js/plugins/conviva.js, test/unit-test-helpers/AnalyticsFrameworkTestUtils.js, test/unit-test-helpers/mock_conviva.js, test/unit-tests/testConviva.js
Conviva
-will now update Conviva of bitrate changes
-added unit tests for bitrate changes
=> [PBI-1799b]

js/plugins/ga.js
-reformatted ga.js to meet with latest code style guidelines
=> [reformat-ga]

js/plugins/ga.js, package.json, test/unit-test-helpers/AnalyticsFrameworkTestUtils.js, test/unit-test-helpers/mock_ga.js, test/unit-tests/testGoogleAnalytics.js
Initial set of unit tests for the Google Analytics Plugins.
=> Ga unit tests

js/plugins/ga.js, test/unit-test-helpers/mock_ga.js, test/unit-tests/testGoogleAnalytics.js
-removed usage of eval
-removed gaMechanism (was not used)
-updated unit tests
=> Ga remove eval

js/framework/AnalyticsConstants.js
Making pull request to master as per Doug's request.  This will ensure the fix gets propagated to future builds.
=> Added description of bitrate change.

js/plugins/conviva.js, test/unit-tests/testConviva.js
-added support to provide Conviva with custom metadata via page level parameter
=> [conviva-metadata]

js/plugins/omniture.js, test/unit-test-helpers/mock_adobe.js, test/unit-tests/testOmniture.js
-added ability to specify SSL mode for Adobe via page level setting
-added unit tests for Adobe Plugin Setup
=> [omniture-ssl]

js/plugins/googleAnalytics.js, test/unit-tests/testGoogleAnalytics.js
-adjusted milestone percents to be 0, 25, 50, 75, and 100
=> [PBI-1925]

js/plugins/conviva.js, test/unit-test-helpers/AnalyticsFrameworkTestUtils.js, test/unit-tests/testConviva.js
Conviva:
-added support for applicationName and streamUrl
-added unit tests for applicationName and streamUrl
=> [PBI-1953]

js/plugins/conviva.js
-Conviva will now report player vendor and version as custom metadata
=> [conviva-player-info]

js/framework/AnalyticsConstants.js, test/unit-tests/testAnalyticsFramework.js
Added new Analytics Event OO.Analytics.EVENTS.SDK_AD_EVENT and new Analytics Event Data EVENT_DATA.SdkAdEventData
=> Player 1256

js/plugins/iq.js, test/unit-tests/testIq.js
add switch to allow player / provider metadata to turn IQ plugin events on / off
=> PLAYER-1377 - load iq in core by default

js/framework/AnalyticsConstants.js, js/plugins/iq.js, test/unit-test-helpers/AnalyticsFrameworkTestUtils.js, test/unit-tests/testIq.js
PR for updating iq.js to handle QoS events
=> Player 1532

js/framework/AnalyticsFramework.js, js/plugins/omniture.js, test/unit-test-helpers/AnalyticsFrameworkTestUtils.js, test/unit-test-helpers/mock_adobe.js, test/unit-tests/testOmniture.js
-The Omniture plugin will now update eVars and props included in params passed in with an embed code change
=> [player-3996]

Jenkinsfile, sonar-project.properties
Added Jenkinsfile
Added sonar-project.propert
=> Player 5250

package-lock.json, package.json, webpack.config.js
Inject Webpack into html5-analytics-plugins repo
=> [PLAYER-4924]: Inject Webpack into html5-analytics-plugins repo
